// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/aws/aws-sdk-go-v2/feature/cloudfront/sign"
	"github.com/aws/aws-sdk-go-v2/service/s3"
)

// Injectors from wire.go:

func initializeRealRouteRegistrar(s3Client *s3.Client, urlSigner *sign.URLSigner, cfg config) routeRegistrar {
	mainMemoryAssetStore := newMemoryAssetStore()
	mainRealS3Adapter := newRealS3Adapter(s3Client)
	string2 := cfg.CloudFrontDomain
	duration := cfg.Expires
	mainRealCloudFrontSigner := newRealCloudFrontSigner(string2, urlSigner, duration)
	mainRealRouteRegistrar := newRealRouteRegistrar(cfg, mainMemoryAssetStore, mainRealS3Adapter, mainRealS3Adapter, mainRealCloudFrontSigner)
	return mainRealRouteRegistrar
}

func initializeMockRouteRegistrar(cfg config) routeRegistrar {
	mainMemoryAssetStore := newMemoryAssetStore()
	mainMockS3Adapter := newMockS3Adapter(cfg)
	mainMockRouteRegistrar := newMockRouteRegistrar(cfg, mainMemoryAssetStore, mainMockS3Adapter)
	return mainMockRouteRegistrar
}
