// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/aws/aws-sdk-go-v2/feature/cloudfront/sign"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"time"
)

// Injectors from wire.go:

func initializeUploadServerDeps(s3Client *s3.Client, urlSigner *sign.URLSigner, cloudfrontDomain string, expires time.Duration) serverDeps {
	mainRealS3Adapter := newRealS3Adapter(s3Client)
	mainRealCloudFrontSigner := newRealCloudFrontSigner(cloudfrontDomain, urlSigner, expires)
	mainMemoryAssetStore := newMemoryAssetStore()
	mainServerDeps := serverDeps{
		S3Presigner:      mainRealS3Adapter,
		S3HeadChecker:    mainRealS3Adapter,
		CloudFrontSigner: mainRealCloudFrontSigner,
		Store:            mainMemoryAssetStore,
	}
	return mainServerDeps
}

// wire.go:

type serverDeps struct {
	S3Presigner      s3PostPolicyPresigner
	S3HeadChecker    s3ObjectHeadChecker
	CloudFrontSigner cloudFrontSigner
	Store            assetStore
}
